version: "3.9"

services:
  redis:
    image: "redis"
    container_name: "redis"
    ports:
      - "6379:6379"
  chat-container:
    build: .
    container_name: "webchat"
    environment:
      - REDIS_HOST=redis
    ports: 
      - "8090:8080"
